name: Semver

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  semver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 18
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'develop'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
